# Generated by Django 6.0.8 on 2026-08-22 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_years', to='institutions.institution')),
            ],
            options={
                'db_table': 'academic_years',
                'ordering': ['institution_id', 'start_date', 'name'],
                'constraints': [models.UniqueConstraint(fields=('institution', 'name'), name='academic_year_institution_name_uniq'), models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='academic_year_valid_dates')],
            },
        ),
    ]
