# Generated by Django 6.0.8 on 2026-08-20 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='institutions.institution')),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['institution_id', 'name'],
                'indexes': [models.Index(fields=['institution'], name='department_institution_idx'), models.Index(fields=['institution', 'is_active'], name='dept_institution_active_idx'), models.Index(fields=['institution', 'name'], name='dept_institution_name_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution', 'code'), name='department_institution_code_uniq')],
            },
        ),
    ]
